# Generated by Django 3.2.7 on 2021-11-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211107_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('HIGH', '1'), ('MEDIUM', '2'), ('LOW', '3')], default='1', max_length=10),
        ),
    ]
