# Generated by Django 3.2.7 on 2021-11-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[('HIGH', 1), ('MEDIUM', 2), ('LOW', 3)], default='1', max_length=10),
        ),
    ]
