# Generated by Django 3.2.7 on 2021-11-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211122_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='name',
            new_name='status',
        ),
    ]
